version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ~/ollama:/root/.ollama
    networks:
      - ollama_net
  load_models:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ollama_net

networks:
  ollama_net: